title = "PerfChrunch"
DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
buildFuture = true
baseURL = "https://webperf-2018.netlify.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
themesDir = "layout_modules"
#theme = "hugo-base-layouts"
preserveTaxonomyNames = true

[blackfriday]
extensionsmask = [
"noIntraEmphasis"
]

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1.0

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 60.0

[mediaTypes]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


[outputFormats]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.sw]
baseName = "sw"
isPlainText = true
mediatype = "application/javascript"
notAlternative = true

[outputs]
home = [
"HTML",
"HEADERS",
"sw"
]

[params]
description = "Build Faster Better Websites with modern tools and techniques"
logo = ""
image_domain = "https://webperf-2018.imgix.net"


# [related]
# includeNewer = true

# [[related.indices]]
# name = "section_name"
# toLower = true
# weight = 100.0

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[social]

[taxonomies]
tag = "tags"