[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.48"

[context.production.environment]
HUGO_ENV = "demo"
#HUGO_ENABLEGITINFO = "true"

[context.slow.environment]
HUGO_ENV = "demo"
command = "hugo --gc"
#HUGO_ENABLEGITINFO = "true"


[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_URL"




# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
